### ISSUE TITLE
Generated Swagger Yaml has incomplete RequestBody Reference

### ISSUE THREAD

**Issue by Oracking** [coding-kitties/flask-swagger-generator#10]
The 'requestBody' field in the generated swagger yaml has a $ref that has an incomplete reference.

Currently, this is the yaml that is generated:

```yaml
paths:
  '/some/route':
    post:
      requestBody:
         $ref: 'name_of_function_request_body'   # <-- Issue is here
```

But this is the valid swagger equivalent

```yaml
paths:
  '/some/route':
    post:
      requestBody:
        $ref: '#/components/requestBodies/name_of_function_request_body'   # <-- Valid Reference
```

This causes swagger UI to break when fed this yaml

**Comment by MDUYN** [comment]
I will start a hotfix branch for this issue

**Comment by Oracking** [comment]
Picking up this issue

**Comment by MDUYN** [comment]
I will close this issue for now.
