### ISSUE TITLE
How can I define query parameters?

### ISSUE THREAD

**Issue by schmidtfx** [coding-kitties/flask-swagger-generator#21]
Hi,

how can I define query parameters for an endpoint?

Thanks

**Comment by fizaashraf37** [comment]
Currently only path parameters can be added. Query parameters are not supported in current version. I will create a feature branch to add this feature.

**Comment by fizaashraf37** [comment]
I have added this functionality in a feature branch with [PR#31](https://github.com/coding-kitties/flask-swagger-generator/pull/31)
