### ISSUE TITLE
Does not support "path" InputType

### ISSUE THREAD

**Issue by BitcoinDBA** [coding-kitties/flask-swagger-generator#7]
### Problem
Flask has a specific string type that accepts slashes, which can be also considered a string.
See [URL Route Registrations](https://flask.palletsprojects.com/en/2.0.x/api/#url-route-registrations)
### Solution
Add 'path' to list of values that return STRING in [InputType.from_string](https://github.com/coding-kitties/flask-swagger-generator/blob/e3fa56f97e57f4d95231e5a0ef8c0bdeb54e7ae3/flask_swagger_generator/utils/input_type.py#L20)

**Comment by MDUYN** [comment]
Opened a branch for and will be scheduled for implementation

**Comment by fizaashraf37** [comment]
I have created a fix branch for this with [PR#30](https://github.com/coding-kitties/flask-swagger-generator/pull/30)

**Comment by MDUYN** [comment]
@fizaashraf37  Could you add some tests. It seems that path does not work in the [swagger editor](https://editor.swagger.io/?_ga=2.132868105.628988796.1666545702-720858107.1666177913l). I added tests in the "test_url_path_parameters.py"

**Comment by fizaashraf37** [comment]
Thanks @MDUYN , I have fixed the issue. Can you tell in which branch you have added this test?

**Comment by MDUYN** [comment]
@fizaashraf37 sorry I forget to mention which branch its on. Its on #34
