### ISSUE TITLE
Flask Version Pinned to 1.1.1

### ISSUE THREAD

**Issue by Oracking** [coding-kitties/flask-swagger-generator#8]
### Problem

Currently, the Flask version in the requirements list is pinned to version 1.1.1. Consequently, when a user lists a different flask version in their own requirements.txt file it causes pip install to fail. This prevents users from using the package if they rely on some functionality of newer versions of Flask for their project.

Even if a user is comfortable with version 1.1.1, there are [issues](https://itsmycode.com/importerror-cannot-import-name-json-from-itsdangerous/) with getting this particular version of Flask to work with flask-swagger-ui, another package used to render the generated swagger yaml as a view.

### Suggested Solution

Unpin the version of Flask and make it >= 1.1.1 as  it does not seem the package strictly relies on that version of Flask

**Comment by MDUYN** [comment]
Opened a branch and will resolve it
